version: 2.1
orbs:
  grafana: grafana/k6@1.1.3
  orb-tools: circleci/orb-tools@10.1.0

workflows:
  load_test:
    jobs:
      - grafana/k6:
          script: Script01.js
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          token-variable: CIRCLE_TOKEN_ORB
          requires:
            - grafana/k6
          filters:
            branches:
              only:
                - master
                - main
